name: Deploy Snowflake Layer

on:
  workflow_dispatch:

jobs:
  build-snowflake-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install snowflake connector (wheel only)
        run: |
          mkdir -p python
          pip install --upgrade pip
          pip install --only-binary=:all: -r requirements-snowflake.txt -t python/

      - name: Zip layer
        run: zip -r snowflake_layer.zip python

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Publish snowflake layer
        run: |
          aws lambda publish-layer-version \
            --layer-name snowflake-layer \
            --zip-file fileb://snowflake_layer.zip \
            --compatible-runtimes python3.11 \
            --description "Snowflake connector layer only"